version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_GA_TRACKING_ID=${VITE_GA_TRACKING_ID}
        - VITE_CONTACT_EMAIL=${VITE_CONTACT_EMAIL}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - webnet
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "com.docker.compose.service=decoration-engineering-web"
      - "description=Decoration Engineering Website"

  # Optional: Add SSL termination with nginx-proxy
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./ssl:/etc/nginx/certs:ro
      - ./nginx-proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    environment:
      - DEFAULT_HOST=your-domain.com
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - webnet
    profiles:
      - ssl

networks:
  webnet:
    driver: bridge

volumes:
  ssl_certs:
    driver: local